### ISSUE TITLE
Pg02 - Explanation dialog

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adilsonv77/nobugssnackbar#91]
```
Explanation CRUD
```

Original issue reported on code.google.com by `adilson...@gmail.com` on 4 Mar 2015 at 3:14

**Comment by adilsonv77** [comment]
It´s everything ok

**Comment by adilsonv77** [comment]
It allows add an empty page

**Comment by thesilent** [comment]
Fixed

**Comment by adilsonv77** [comment]
- It still allows add an empty page. It must gives the error message and doesn't close the window
- Resizing the dialog must also repositioning the buttons
