### ISSUE TITLE
Pg08 - Commands

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adilsonv77/nobugssnackbar#97]
```
Commands CRUD
```

Original issue reported on code.google.com by `adilson...@gmail.com` on 4 Mar 2015 at 3:20

**Comment by thesilent** [comment]
Closed

**Comment by adilsonv77** [comment]
In the items list must only show the items of the currently category selected.

**Comment by adilsonv77** [comment]
The labels maybe must be provided by the messages properties.

**Comment by adilsonv77** [comment]
The issue about the labels is done.

**Comment by thesilent** [comment]
Fixed

**Comment by adilsonv77** [comment]
The selection is not ok
