### ISSUE TITLE
Transform de img tag in imghex tag into the explanation page and hint content

### ISSUE THREAD

**Issue by adilsonv77** [adilsonv77/nobugssnackbar#99]

**Comment by thesilent** [comment]
Accepted

**Comment by thesilent** [comment]
Done!

**Comment by adilsonv77** [comment]
I tried adding this two images into a page:
- https://christiesmith21.files.wordpress.com/2010/10/3964006080_5bab1931592.jpg?w=300&h=221
- https://blogs.chapman.edu/wp-content/uploads/sites/26/2013/02/dosomething-05-800x510.jpg

and throw this exception:
Numbers of source Raster bands and source color space components do not match

**Comment by adilsonv77** [comment]
When the image is not supported, show an error message to the user and stay in the dialog (dont close it).

**Comment by adilsonv77** [comment]
The dialog is closed. It must keep opened.

**Comment by adilsonv77** [comment]
Maybe the strategy on definition of the imghex id must be improved. We need to guarantee that the ID will not repeat in the entire game. 

You should use the currently datetime in numeric format (long) as the ID value.
